/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/mock-server/specs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register an OpenAPI spec
         * @description Registers a YAML or JSON OpenAPI spec. Re-posting the same specName + content is idempotent — returns the existing specId.
         */
        post: operations["registerSpec"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mock-server/specs/{specId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a registered spec */
        get: operations["getSpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mock-server/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all mock servers */
        get: operations["listMockServers"];
        put?: never;
        /**
         * Create a mock server
         * @description Creates a mock server for a previously registered spec. Auto-generates default response variants for every operation in the spec.
         */
        post: operations["createMockServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mock-server/servers/{mockServerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a mock server */
        get: operations["getMockServer"];
        put?: never;
        post?: never;
        /** Delete a mock server */
        delete: operations["deleteMockServer"];
        options?: never;
        head?: never;
        /**
         * Update a mock server
         * @description Rename, enable/disable, or change the default response strategy.
         */
        patch: operations["patchMockServer"];
        trace?: never;
    };
    "/mock-server/servers/{mockServerId}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export a mock server
         * @description Returns the spec, server config, and all variants as a single portable JSON document.
         */
        get: operations["exportMockServer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mock-server/servers/{mockServerId}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List response variants */
        get: operations["listVariants"];
        put?: never;
        /** Create a response variant */
        post: operations["createVariant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mock-server/servers/{mockServerId}/variants/{variantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a response variant */
        put: operations["updateVariant"];
        post?: never;
        /** Delete a response variant */
        delete: operations["deleteVariant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mock-server/servers/{mockServerId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get recent request logs */
        get: operations["getLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mock-server/servers/{mockServerId}/spec-operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List parsed operations from the spec
         * @description Returns the operations parsed from the registered OpenAPI spec when the mock server was created. Useful for the UI Endpoints tab — provides HTTP method, path, and operationId.
         */
        get: operations["listSpecOperations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mock-server/servers/{mockServerId}/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List operation configs */
        get: operations["listOperationConfigs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mock-server/servers/{mockServerId}/operations/{operationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update an operation config
         * @description Enable/disable an operation or override its response strategy.
         */
        patch: operations["patchOperationConfig"];
        trace?: never;
    };
    "/mock/{mockServerId}/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Send a mock GET request */
        get: operations["mockRequestGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @default RANDOM
         * @enum {string}
         */
        ResponseStrategy: "RANDOM" | "SEQUENTIAL" | "ROUND_ROBIN" | "DEFAULT_ONLY";
        /** @description An operation parsed from the registered OpenAPI spec */
        SpecOperation: {
            operationId?: string;
            /** @example GET */
            httpMethod?: string;
            /** @example /users/{id} */
            path?: string;
            /** @example 200 */
            successStatusCode?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        RegisterSpecRequest: {
            /** @example petstore */
            specName: string;
            /** @description Raw YAML or JSON OpenAPI spec */
            specContent: string;
        };
        ApiSpec: {
            /** Format: uuid */
            specId?: string;
            specName?: string;
            specVersion?: string;
            specHash?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateMockServerRequest: {
            /** Format: uuid */
            specId: string;
            /** @example petstore-mock */
            name: string;
            defaultStrategy?: components["schemas"]["ResponseStrategy"];
        };
        PatchMockServerRequest: {
            name?: string;
            isEnabled?: boolean;
            defaultStrategy?: components["schemas"]["ResponseStrategy"];
        };
        MockServer: {
            /** Format: uuid */
            mockServerId?: string;
            /** Format: uuid */
            specId?: string;
            name?: string;
            defaultStrategy?: components["schemas"]["ResponseStrategy"];
            isEnabled?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        VariantRequest: {
            operationId: string;
            responseName: string;
            /** @example 200 */
            statusCode: string;
            responseBody: string;
            headers?: {
                [key: string]: string;
            };
            /** @default false */
            isDefault: boolean;
            /** @default 0 */
            displayOrder: number;
        };
        MockResponseVariant: components["schemas"]["VariantRequest"] & {
            /** Format: uuid */
            variantId?: string;
            /** Format: uuid */
            mockServerId?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        MockRequestLog: {
            /** Format: uuid */
            logId?: string;
            /** Format: uuid */
            mockServerId?: string;
            operationId?: string;
            /** @example GET */
            requestMethod?: string;
            requestPath?: string;
            requestHeaders?: {
                [key: string]: string;
            };
            requestBody?: string;
            responseStatusCode?: string;
            responseBody?: string;
            /** Format: uuid */
            variantId?: string;
            responseTimeMs?: number;
            /** Format: date-time */
            requestedAt?: string;
        };
        MockOperationConfig: {
            /** Format: uuid */
            configId?: string;
            /** Format: uuid */
            mockServerId?: string;
            operationId?: string;
            isEnabled?: boolean;
            strategyOverride?: components["schemas"]["ResponseStrategy"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        PatchOperationConfigRequest: {
            isEnabled?: boolean;
            responseStrategy?: components["schemas"]["ResponseStrategy"];
        };
        MockServerExport: {
            /** @example 1.0 */
            version?: string;
            spec?: components["schemas"]["ApiSpec"];
            mockServer?: components["schemas"]["MockServer"];
            variants?: components["schemas"]["MockResponseVariant"][];
        };
    };
    responses: never;
    parameters: {
        mockServerId: string;
        specId: string;
        variantId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerSpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterSpecRequest"];
            };
        };
        responses: {
            /** @description Spec registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiSpec"];
                };
            };
        };
    };
    getSpec: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                specId: components["parameters"]["specId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiSpec"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listMockServers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MockServer"][];
                };
            };
        };
    };
    createMockServer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMockServerRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MockServer"];
                };
            };
        };
    };
    getMockServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mockServerId: components["parameters"]["mockServerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MockServer"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteMockServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mockServerId: components["parameters"]["mockServerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patchMockServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mockServerId: components["parameters"]["mockServerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchMockServerRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MockServer"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    exportMockServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mockServerId: components["parameters"]["mockServerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Export document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MockServerExport"];
                };
            };
        };
    };
    listVariants: {
        parameters: {
            query?: {
                /** @description Filter variants by operationId */
                operationId?: string;
            };
            header?: never;
            path: {
                mockServerId: components["parameters"]["mockServerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MockResponseVariant"][];
                };
            };
        };
    };
    createVariant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mockServerId: components["parameters"]["mockServerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariantRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MockResponseVariant"];
                };
            };
        };
    };
    updateVariant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mockServerId: components["parameters"]["mockServerId"];
                variantId: components["parameters"]["variantId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariantRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MockResponseVariant"];
                };
            };
        };
    };
    deleteVariant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mockServerId: components["parameters"]["mockServerId"];
                variantId: components["parameters"]["variantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getLogs: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                mockServerId: components["parameters"]["mockServerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MockRequestLog"][];
                };
            };
        };
    };
    listSpecOperations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mockServerId: components["parameters"]["mockServerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecOperation"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listOperationConfigs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mockServerId: components["parameters"]["mockServerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MockOperationConfig"][];
                };
            };
        };
    };
    patchOperationConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mockServerId: components["parameters"]["mockServerId"];
                operationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchOperationConfigRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MockOperationConfig"];
                };
            };
        };
    };
    mockRequestGet: {
        parameters: {
            query?: never;
            header?: {
                /** @description Force a specific HTTP status code to be returned */
                "X-spec0-Preferred-Response-Code"?: string;
                /** @description Override which operationId is matched */
                "X-Mock-Operation-Id"?: string;
            };
            path: {
                mockServerId: components["parameters"]["mockServerId"];
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mock response (status code may vary per variant) */
            200: {
                headers: {
                    "X-spec0-Mock-Response"?: "true";
                    "X-spec0-Mock-Operation-Id"?: string;
                    "X-spec0-Mock-Variant-Id"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
